name: qr_code_startup
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  go_router: ^14.2.3
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.11
  permission_handler: ^11.3.1
  local_auth: ^2.3.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
